/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Category, Unit, Product, Sale, SaleType, SaleStatus, PaymentMethod } from "./types";

export const MOCK_PRODUCTS: Product[] = [
// ... (rest of MOCK_PRODUCTS)
  {
    id: "1",
    code: "CAB-SUB-325",
    name: "Cable Subterráneo 3x2.5mm²",
    brand: "Prysmian",
    category: Category.Cables,
    unit: Unit.Metro,
    stockActual: 156.3,
    stockMinimo: 30,
    iva: 21,
    priceCosto: 950,
    pricePublico: 1925,
    priceGremio: 1480,
    priceMayorista: 1280,
  },
  {
    id: "2",
    code: "CAB-TAL-315",
    name: "Cable TALLER 3x1.5mm²",
    brand: "Kalop",
    category: Category.Cables,
    unit: Unit.Metro,
    stockActual: 225.8,
    stockMinimo: 50,
    iva: 21,
    priceCosto: 580,
    pricePublico: 1155,
    priceGremio: 890,
    priceMayorista: 770,
  },
  {
    id: "3",
    code: "CAN-COR-34",
    name: "Caño Corrugado 3/4\" x 25m",
    brand: "Daisa",
    category: Category.CanosTubos,
    unit: Unit.Rollo,
    stockActual: 45.0,
    stockMinimo: 10,
    iva: 21,
    priceCosto: 3200,
    pricePublico: 6380,
    priceGremio: 4900,
    priceMayorista: 4200,
  },
  {
    id: "4",
    code: "TER-DIF-25",
    name: "Disyuntor Diferencial 25A 30mA",
    brand: "ABB",
    category: Category.Termica,
    unit: Unit.Unidad,
    stockActual: 18.0,
    stockMinimo: 5,
    iva: 21,
    priceCosto: 12000,
    pricePublico: 24200,
    priceGremio: 18600,
    priceMayorista: 16100,
  },
  {
    id: "5",
    code: "ILU-LED-9F",
    name: "Lámpara LED 9W E27 Fría",
    brand: "Philips",
    category: Category.Iluminacion,
    unit: Unit.Unidad,
    stockActual: 230.0,
    stockMinimo: 20,
    iva: 21,
    priceCosto: 650,
    pricePublico: 1320,
    priceGremio: 1020,
    priceMayorista: 880,
  },
];

export const MOCK_SALES: Sale[] = [
  {
    id: "101",
    date: "07/03/26 18:53",
    type: SaleType.Presupuesto,
    client: "dadfa",
    paymentMethod: PaymentMethod.EfectivoTransferencia,
    items: [{ product: MOCK_PRODUCTS[0], quantity: 1 }],
    itemsCount: 1,
    total: 1500,
    status: SaleStatus.Pendiente,
    isDeclared: false,
  },
  {
    id: "102",
    date: "07/03/26 18:52",
    type: SaleType.FacturaC,
    client: "Consumidor Final",
    paymentMethod: PaymentMethod.TarjetaDebito,
    items: [
      { product: MOCK_PRODUCTS[1], quantity: 2 },
      { product: MOCK_PRODUCTS[2], quantity: 1 }
    ],
    itemsCount: 2,
    total: 42575,
    status: SaleStatus.Confirmada,
    isDeclared: true,
  },
  {
    id: "103",
    date: "07/03/26 18:42",
    type: SaleType.FacturaA,
    client: "Electro Sur SRL",
    paymentMethod: PaymentMethod.TarjetaCredito,
    items: [{ product: MOCK_PRODUCTS[3], quantity: 1 }],
    itemsCount: 1,
    total: 71200,
    status: SaleStatus.Confirmada,
    isDeclared: true,
  },
  {
    id: "104",
    date: "07/03/26 17:15",
    type: SaleType.FacturaB,
    client: "Mantenimientos ABC",
    paymentMethod: PaymentMethod.QR,
    items: [
      { product: MOCK_PRODUCTS[0], quantity: 10 },
      { product: MOCK_PRODUCTS[1], quantity: 5 }
    ],
    itemsCount: 5,
    total: 115800,
    status: SaleStatus.Confirmada,
    isDeclared: false,
  },
];
